CREATE TABLE CUSTOMER(
	CID INT AUTO_INCREMENT,
	USERNAME VARCHAR(15),
	PASSWORD VARCHAR(20),
	MOBILENO VARCHAR(10),
	MAILID VARCHAR(20),
	PRIMARY KEY (CID)
);
CREATE TABLE EMPLOYEE (
	EID INT AUTO_INCREMENT,
	ENAME VARCHAR(15),
	PASSWORD VARCHAR(20),
	MOBILENO VARCHAR(10),
	MAILID VARCHAR(20),
	PRIMARY KEY(EID)
);
CREATE TABLE PRODUCTS (
	PID INT AUTO_INCREMENT,
	PNAME VARCHAR(15),
	PRICE INT,
	QUANTITY INT,
	PRIMARY KEY(PID)
);
CREATE TABLE EMP_PRODUCT (
	PID INT,
	EID INT,
	FOREIGN KEY(PID) REFERENCES PRODUCTS(PID),
	FOREIGN KEY(EID) REFERENCES EMPLOYEE(EID),
	PRIMARY KEY(PID, EID)
);

CREATE TABLE ORDERS(
	OID INT AUTO_INCREMENT,
	CID INT,
	ORDERDATE DATE,
	ORDERSTATUS VARCHAR(1), -- CONFIRMED C, SHIPPED S, DELIVERED D
	FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
	PRIMARY KEY(OID, CID)
);
CREATE TABLE PRODUCTS_ORDERED(
	OID INT,
	PID INT,
	QUANTITY INT,
	FOREIGN KEY(OID) REFERENCES ORDERS(OID),
	FOREIGN KEY(PID) REFERENCES PRODUCTS(PID),
	PRIMARY KEY(OID, PID)
);
CREATE TABLE CART(
	PID INT,
	CID INT,
	QUANTITY INT,
	FOREIGN KEY(PID) REFERENCES PRODUCTS(PID),
	FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
	PRIMARY KEY(PID, CID)
);
