/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket.Users.Admin;

import supermarket.login.LoginPage;
import javax.swing.JOptionPane;

/**
 *
 * @author Narayanan Krishna
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form admin_dash
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ReviewProductData = new javax.swing.JButton();
        ReviewEmployeeData = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        ReviewOrderData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome Admin");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 280, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("S-Market Online v1.0");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        ReviewProductData.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        ReviewProductData.setText("Review Product data");
        ReviewProductData.setBorder(new javax.swing.border.MatteBorder(null));
        ReviewProductData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewProductDataActionPerformed(evt);
            }
        });
        getContentPane().add(ReviewProductData, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 230, 60));

        ReviewEmployeeData.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        ReviewEmployeeData.setText("Review employee data");
        ReviewEmployeeData.setBorder(new javax.swing.border.MatteBorder(null));
        ReviewEmployeeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewEmployeeDataActionPerformed(evt);
            }
        });
        getContentPane().add(ReviewEmployeeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 220, 60));

        Logout.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        Logout.setText("Logout");
        Logout.setBorder(new javax.swing.border.MatteBorder(null));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 120, 70));

        ReviewOrderData.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        ReviewOrderData.setText("Review Order Data");
        ReviewOrderData.setBorder(new javax.swing.border.MatteBorder(null));
        ReviewOrderData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewOrderDataActionPerformed(evt);
            }
        });
        getContentPane().add(ReviewOrderData, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 210, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/shopping-cart--v2_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
this.setVisible(false);
JOptionPane.showMessageDialog(null, "You've been successfully logged out\n");
new LoginPage().setVisible(true); 
    }//GEN-LAST:event_LogoutActionPerformed

    private void ReviewEmployeeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewEmployeeDataActionPerformed
this.setVisible(false);         
new AdminEmployeeDashboard().setVisible(true);
    }//GEN-LAST:event_ReviewEmployeeDataActionPerformed

    private void ReviewProductDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewProductDataActionPerformed
this.setVisible(false);         
new AdminProductDashboard().setVisible(true);         
    }//GEN-LAST:event_ReviewProductDataActionPerformed

    private void ReviewOrderDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewOrderDataActionPerformed
    this.setVisible(false);         
new AdminOrdersDashboard().setVisible(true);     
    }//GEN-LAST:event_ReviewOrderDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton ReviewEmployeeData;
    private javax.swing.JButton ReviewOrderData;
    private javax.swing.JButton ReviewProductData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
